CREATE DATABASE DKHP;
USE DKHP;

CREATE TABLE TINH(
	MaTinh VARCHAR(5) PRIMARY KEY,
	TenTinh VARCHAR(40) 
)

CREATE TABLE HUYEN(
	MaHuyen VARCHAR(5) PRIMARY KEY,
	tenHuyen VARCHAR(40),
	ThuocTinh VARCHAR(5) FOREIGN KEY REFERENCES TINH(MaTinh),
	VungSau INT
)

CREATE TABLE DOITUONG(
	MaDT VARCHAR(5) PRIMARY KEY,
	TenDT VARCHAR(40),
	MienGiam FLOAT,
	DoUuTien INT	
)

CREATE TABLE KHOA(
	MaKhoa VARCHAR(4) PRIMARY KEY,
	TenKhoa VARCHAR(40)
)

CREATE TABLE NGANH(
	MaNganh VARCHAR(4) PRIMARY KEY,
	TenNganh VARCHAR(40),
	ThuocKhoa VARCHAR(4) FOREIGN KEY REFERENCES KHOA(MaKhoa)
)

CREATE TABLE SINHVIEN(
	MaSV VARCHAR(8) PRIMARY KEY,
	TenSV VARCHAR(40),
	NgaySinh SMALLDATETIME,
	GioiTinh INT,
	DoiTuong VARCHAR(5) FOREIGN KEY REFERENCES DOITUONG(MaDT),
	Huyen VARCHAR(5) FOREIGN KEY REFERENCES HUYEN(MaHuyen),
	Tinh VARCHAR(5) FOREIGN KEY REFERENCES TINH(MaTinh),
	NganhHoc VARCHAR(4) FOREIGN KEY REFERENCES NGANH(MaNganh)
)

CREATE TABLE LOAIMON(
	MaLoaiMon VARCHAR(5) PRIMARY KEY,
	TenLoaiMon VARCHAR(40),
	SoTinChi INT,
	GiaTien MONEY
)

CREATE TABLE MONHOC(
	MaMon VARCHAR(5) PRIMARY KEY,
	TenMon VARCHAR(40),
	SoTiet INT,
	LoaiMon VARCHAR(5) FOREIGN KEY REFERENCES LOAIMON(MaLoaiMon)
)

CREATE TABLE CHUONGTRINH(
	NganhHoc VARCHAR(4) FOREIGN KEY REFERENCES NGANH(MaNganh),
	Khoa VARCHAR(4)  FOREIGN KEY REFERENCES KHOA(MAKHOA),
	HocKy INT,
	MonHoc VARCHAR(5) FOREIGN KEY REFERENCES MONHOC(MAMON),
	GhiChu VARCHAR(40),
	PRIMARY KEY (NganhHoc, Khoa, HocKy, MonHoc)
)

CREATE TABLE HOCKYCHINH(
	MaHKC INT PRIMARY KEY,
	TenHKC VARCHAR(40)
)

CREATE TABLE DSHOCKY(
	MaHK VARCHAR(5) PRIMARY KEY,
	HocKy INT FOREIGN KEY REFERENCES HOCKYCHINH (MaHKC),
	NamHoc INT,
	ThoiHan SMALLDATETIME
)

CREATE TABLE MONHOCMO(
	MaHK VARCHAR(5) FOREIGN KEY REFERENCES DSHOCKY(MaHK),
	MonHoc VARCHAR(5) FOREIGN KEY REFERENCES MONHOC(MAMON),
	PRIMARY KEY (MaHK, MonHoc)
)

CREATE TABLE PHIEUDK(
	SoPhieu VARCHAR(5) PRIMARY KEY,
	MaSV VARCHAR(8) FOREIGN KEY REFERENCES SINHVIEN(MaSV),
	MaHK VARCHAR(5) FOREIGN KEY REFERENCES DSHOCKY(MaHK),
	NgayLap SMALLDATETIME
)

CREATE TABLE DKHOCPHAN(
	SoPhieu VARCHAR(5) FOREIGN KEY REFERENCES PHIEUDK (SoPhieu),
	MonHoc VARCHAR(5),
	PRIMARY KEY (SoPhieu, MonHoc)
)

CREATE TABLE THUHOCPHI(
	MaThuPhi VARCHAR(5) PRIMARY KEY,
	SoPhieu VARCHAR(5) FOREIGN KEY REFERENCES PHIEUDK (SoPhieu),
	SoTienThu MONEY,
	NgayThu SMALLDATETIME
)