-- DELETE DATABASE
USE master
GO
DROP DATABASE DKHP;

-- LIST ALL DATABASE
SELECT name, database_id, create_date  
FROM sys.databases;  
GO 

-- LIST ALL TABLE IN DB
SELECT *
FROM INFORMATION_SCHEMA.TABLES;
GO

-- DÙNG DATABASE NHÓM
use "D:\DANGKYHOCPHAN\DATABASE\DKHP.MDF"
GO
-- TEST APP
use "E:\TEMP\DANGKYHOCPHAN\DANGKYHOCPHAN\BIN\DEBUG\DKHP.MDF"
GO

-- TEST
USE DKHP
GO

INSERT INTO DKHOCPHAN VALUES ('090112922','IT001');

SELECT * FROM THUHOCPHI
SELECT * FROM CHUAHTHP

UPDATE CHUAHTHP SET SoTienConLai =1234 WHERE SoPhieu = 000112022

INSERT INTO THUHOCPHI VALUES ('1302','000112022',6000000,CURRENT_TIMESTAMP);

SELECT Count(MaSV) from SINHVIEN

-- TRIGER kiểm tra xem có tồn tại MaSV trong csdl hay không
CREATE TRIGGER KIEM_TRA_MSSV_THUHOCPHI
FOR INSERT, UPDATE
AS
BEGIN
declare @MaSV VARCHAR(8), TON_TAI_MSSV INT
SELECT @MaSV = MaSV from inserted
SELECT @TON_TAI_MSSV = count(MaSV) from SINHVIEN where MaSV = @MaSV
IF (@TON_TAI_MSSV < 1)
	BEGIN
	PRINT 'KHONG TON TAI MASV'
	ROLLBACK TRANSACTION
	END
END
